alias checktemp='/opt/vc/bin/vcgencmd measure_temp'
alias shutdown='~/.scripts/backupdb/backup.sh;sudo shutdown -h now'
alias reboot='sudo reboot'
alias cdusb='cd /media'
alias ka='cd ~/.kalite'
#alias sync='sudo service ka-lite stop;sudo service nginx stop;kalite manage syncmodels'
#alias syncverbose=' sudo service ka-lite stop;sudo service nginx stop;kalite manage syncmodels --verbose'
alias l='ls -ltr'
alias whoru='cd ~/.scripts/identify/;python identify.py'
alias swapdb='~/.scripts/swapdb/swapdb' 
alias fixcrazy='sudo service ka-lite stop;sudo service nginx stop;sudo ~/.scripts/reporting/fix_crazy/fixcrazy'
alias alldata='~/.scripts/reporting/alldata.sh'
alias monthend='~/.scripts/reporting/monthend.sh'
alias restartka='sudo service nginx restart;sudo service ka-lite restart;chmod +x ~/.baseline_testing/scripts/startup_script;~/.baseline_testing/scripts/startup_script'
alias backup='sudo service ka-lite stop;sudo service nginx stop;~/.scripts/backupdb/backup.sh'
alias upgrade='~/upgrade'
alias restore_learner='cd ~/.scripts/reporting;python restore_learner.py;cd ~'
alias tunnel='~/.scripts/ssh_tunnel/create_ssh_tunnel.sh'

#baseline aliases
alias baseline='chmod +x ~/.baseline_testing/scripts/reporting/baseline.sh;~/.baseline_testing/scripts/reporting/baseline.sh'
alias restartbl='chmod +x ~/.baseline_testing/scripts/startup_script;~/.baseline_testing/scripts/startup_script'
alias getkausers='chmod +x ~/.baseline_testing/scripts/start_users_extraction.sh;~/.baseline_testing/scripts/start_users_extraction.sh'
