#!/bin/bash

cd ~/.scripts || exit
git reset --hard origin/namibia
git pull origin namibia
./setup.sh

# Pull latest changes to baseline_testing
cd ~/.baseline_testing || exit
git reset --hard origin/namibia
git pull origin namibia

# Pull latest changes to Kolibri helper scripts
cd ~/.kolibri_helper_scripts || exit
git reset --hard origin/namibia
git pull origin namibia