# Import tables and generate filename script
source('/home/ka-lite/.scripts/reporting/get_dbtables.R')
source('/home/ka-lite/.scripts/reporting/generate_filename.R')

# Function to get all data in db from beginning of time until month that user specifies
alldata <- function(year_month) {
  #with user input from command line, create complete date by prefixing with 01
  upper_limit <- paste("01-",year_month,sep="")
  #regular expression to check if the user input is a valid month and year, and in the form mm-yy
  regexp <-'((?:(?:[0-2]?\\d{1})|(?:[3][01]{1}))[-:\\/.](?:[0]?[1-9]|[1][012])[-:\\/.](?:(?:\\d{1}\\d{1})))(?![\\d])'
  #check if its a valid date and correct number of characters. stops the program if input not fit
  if(!(grepl(pattern = regexp,x=upper_limit,perl = TRUE)) | (nchar(upper_limit) > 8)) stop("Please enter a valid month and year mm-yy e.g '12-16'")
  # with variable from above date, parse into date and get last day in month then convert into proper date format
  upper_limit <- as.Date(timeLastDayInMonth(strftime(upper_limit,"%d-%m-%y"),format = "%y-%m-%d"))
  # get exercises per user - group userlog rows by user_id then get max last active date and summarize total exercises, exercises complete
  #exercises_per_user <- main_exerciselog %>% filter(upper_limit >= as.Date(latest_activity_timestamp)) %>% group_by(user_id) %>% summarize(exercises_attempted = n(), total_exercises = sum(complete))
  exercises_per_user <- main_exerciselog %>% group_by(user_id) %>% summarize(exercises_attempted = n(), total_exercises = sum(complete))
  #almost the same as query above, except we dont care about anything except total videos watched
  #videos_per_user <- main_videolog %>% filter(upper_limit >= as.Date(latest_activity_timestamp)) %>% group_by(user_id) %>% summarize(total_videos = n())
  videos_per_user <- main_videolog %>% group_by(user_id) %>% summarize(total_videos = n())
  #first summarizes user activity from userlog summary, then produces complete aggregation of data after joining users(r_join),exercises per user,videos per user, facility, group
  complete_summary <- main_userlogsummary %>% group_by(user_id) %>% summarise(total_hours = sum(total_seconds)/3600, total_logins = n(), last_active_date = max(as.Date(last_activity_datetime))) %>% right_join(users, by = c("user_id" = "id")) %>% left_join(exercises_per_user, by = "user_id") %>% left_join(videos_per_user, by = "user_id") %>% left_join(facilities, by = c("facility_id" = "id")) %>% left_join(groups, by = c("group_id" = "id")) %>% mutate(month_end=rep(strftime(upper_limit,format = "%d-%m-%y")))
  # selecting fields to be written to csv file and changing column names appropriately
  rpt <- complete_summary %>% select(user_id,first_name,last_name,username,name.y,total_logins,total_hours,total_exercises,total_videos,month_end,exercises_attempted,name.x,last_active_date) %>% rename(centre = name.x, group = name.y, id = user_id)
  # create csv file with filename generated by based on name of report and user input
  write.csv(rpt, file = generate_filename("data.all_",year_month) ,col.names = FALSE, row.names = FALSE,na="0")
  #print success messgae
  system("echo Report extracted successfully!")
  #dont save workspace
  quit(save="no")
}

# fetch user input from the command line
input<- commandArgs(TRUE)

# run function with user input as argument
alldata(input)
