#!/bin/bash
# inline string replacement using sed
sudo sed -i -e 's/SESSION_IDLE_TIMEOUT = getattr(local_settings, "SESSION_IDLE_TIMEOUT", 0)/SESSION_IDLE_TIMEOUT = getattr(local_settings, "SESSION_IDLE_TIMEOUT", 750)/g' /usr/lib/python2.7/dist-packages/kalite/settings/base.py