#!/bin/bash
# Script to swap databases when a single device is running on 2 databases
if [ ! -d ~/.kalite/database/swapdb ]; then
  # exits if the swap directory does not exist
  echo "Swap directory does not exist: skipping"
  exit 0
fi

if [ ! -f ~/.kalite/database/swapdb/data.swap.sqlite ]; then
  # exits if the swap db file does not exist
  echo "Swap db file does not exist: skipping"
  exit 0
fi

# First stop the kalite server (takes a few minutes)
echo "stopping ka-lite server, please wait..."
sudo  service nginx stop
sudo  service ka-lite stop

# Once server stopped switch db files
cd ~/.kalite/database/

# swapping db files
mv ~/.kalite/database/swapdb/data.swap.sqlite .
mv data.sqlite ~/.kalite/database/swapdb/data.swap.sqlite
mv data.swap.sqlite data.sqlite 

# Re start kalite server (takes a few minutes)
echo "restarting ka-lite server, please wait..."
sudo  service nginx restart
sudo  service ka-lite restart

# When server re-started, run whoru script
cd ~/.scripts/identify
echo "Database swapped - details of active database is:"
python identify.py
